### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by stevenvandorpe** [x011/dload#5]
First of all: thanks for the great library!

I am getting the following error when using` dload.git_clone`. I tried with different repo's but get the same error.

```
dload.git_clone("https://github.com/aaaa/aaaa.git", clone_dir=LOCAL_DST)
None
Traceback (most recent call last):
  File "C:\Users\a316283\AppData\Local\Continuum\anaconda3\lib\site-packages\dload\__init__.py", line 256, in save_unzip
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
  File "C:\Users\a316283\AppData\Local\Continuum\anaconda3\lib\zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "C:\Users\a316283\AppData\Local\Continuum\anaconda3\lib\zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Any ideas?

Thanks!

**Comment by kallewesterling** [comment]
Same here. Any resolve on this issue @x011 ?

**Comment by gruummy** [comment]
Could it be that there is no "master" branch in your repo which you want to clone ?

The branch name which will be downloaded is currently hardcoded to "master" if i understand it right.
https://github.com/x011/dload/blob/master/dload/__init__.py#L280

**Comment by kallewesterling** [comment]
That's frustrating given GitHub's [efforts to remove the unnecessary references to histories of enslavement](https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month). @x011 it might be something you want to address in the code.

**Comment by x011** [comment]
Fixed on https://github.com/x011/dload/pull/12
